apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-t3aj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dpgf-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-t3aj@sha256:140f6a3f1fec74f7fa44c614b7cf816add98af7b28f8ee8b9f3882d3e097a296
        name: my-nodejs
        resources: {}
status: {}
